### ISSUE TITLE
Decimal precision issue

### ISSUE THREAD

**Issue by grigorgeous** [CurrencyCloud/currencycloud-net#30]
Hi,

We've faced the following problem: when we send a 5 EUR payment, everything went smooth but 5.55 EUR payment always returned us an error. It took us some time to figure out that even though amount kept as 5.55 in database, Entity Framework converted it to 5.5500 (with bigger scale) which resulted in a failure when sending such an amount to your test environment.

So that I propose you to check the precision/scale of the decimal and either trim zeros (change scale), or return a corresponding error so that it would be easier to figure out what caused the problem.

**Comment by EAddario** [comment]
Hi @grigorgeous the SDK will serialize / deserialize to the appropriate types (decimal in the case of monetary amounts) and the choice of precision is left to the consumer application. For example, 

This snippet will successfully create a payment:
```c#
var payment = await client.CreatePaymentAsync(new Payment
{
    BeneficiaryId = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
    Currency = "EUR",
    Amount = Convert.ToDecimal("5"),
    Reason = "Investment",
    Reference = "REF-12345"
    PaymentType = "regular",
    UltimateBeneficiaryName = "Francis Wayland Thurston"
    UniqueRequestId = Guid.NewGuid().ToString()
});
```
and so will this:
```c#
var payment = await client.CreatePaymentAsync(new Payment
{
    BeneficiaryId = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
    Currency = "EUR",
    Amount = Convert.ToDecimal("5.00"),
    Reason = "Investment",
    Reference = "REF-12345"
    PaymentType = "regular",
    UltimateBeneficiaryName = "Francis Wayland Thurston"
    UniqueRequestId = Guid.NewGuid().ToString()
});
```
whereas this will generate an exception **BadRequestException**
```c#
var payment = await client.CreatePaymentAsync(new Payment
{
    BeneficiaryId = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
    Currency = "EUR",
    Amount = Convert.ToDecimal("5.000"),
    Reason = "Investment",
    Reference = "REF-12345"
    PaymentType = "regular",
    UltimateBeneficiaryName = "Francis Wayland Thurston"
    UniqueRequestId = Guid.NewGuid().ToString()
});
```
```
ApiException -> BadRequestException
---
platform: 5.4.1.7 (2017-06/e66d9abbb27 Wed Oct 25 12:10:41 EDT 2017)
request:
  parameters: {}
  verb: POST
  url: https://devapi.currencycloud.com/v2/payments/create
response:
  status_code: 400
  date: Thu, 16 May 2019 08:39:01 GMT
  request_id: e4be9cbc-5ad9-45f6-af0e-a9a42b442184
errors:
- field: amount_format
  code: invalid_amount_format
  message: EUR only supports up to 2 decimal places
  params: {}
```
From your comment we assume you are using EF to manipulate and/or persist CurrencyCloud.Entity objects (like _Payment_) but it's not clear under what circumstances you are encountering the error. Could you post an example?
